config/routes.rb
Epilady::Application.routes.draw do
        
  authenticated :user do
    root :to => 'reads#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :reads
  resources :prints
  resources :patients do
          
    resources :reports do
            get 'print'        
      resources :conclusions
      resources :tumors
      resources :malformacions
      resources :displasia
      resources :esclerosis
    end
  end
end

app/models/print.rb
class Print < ActiveRecord::Base
  belongs_to :patient
  
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  def index
    @patients=Patient.all
    @report = Report.where(user_id: current_user.id)
    
  end
  
  def show
    @patients=Patient.find(:id)
    @reports = Report.where(user_id: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
    
  end
  
  
  
  
end

app/views/prints/index.html.erb
<div class="page-header">
  <h2>Generar reporte para imprimir</h2>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Paciente</th>
      <th>Lecturas</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><strong><%= patient.name %></strong></td>
	<%report=@report.where(patient_id:patient.id, equipment:"3T").first%>
	
        <td><%=link_to "mostrar reporte", patient_report_print_path(patient,report), :format=> :pdf, class: 'btn btn-primary enabled' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/prints/show.html.erb
<div class="page-header lead">Editar reporte para el paciente tal
	<strong>
		<%=@report.label%>
	</strong></div>
	</strong>


<blockquote><p>
	<h4>Información clínica del paciente:</h4>
	<%if @report.equipment=="3T" %>
		<%=@patient.infoclinica3 %>
	<%else%>
		<%=@patient.infoclinica15%>
	<%end%>
</blockquote></p>

<small>En cada paciente evalúe los siguientes 4 ítems. Después lea la petición del especialista y evalué lo que se solicita según la sospecha clínica de cada paciente Marque con una X en la pregunta de cada ítem si y sólo si considera que la resonancia presenta dichos hallazgos.</small>
<br>
<%= render :partial => 'form' %>

<%= link_to 'Atras', patient_reports_path(equipment:@report.equipment,label:params[:label]) %>