config/routes.rb
Epilady::Application.routes.draw do
        
  authenticated :user do
    root :to => 'reads#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :reads
  resources :prints
  resources :patients do
          
    resources :reports do
            get 'print'        
      resources :conclusions
      resources :tumors
      resources :malformacions
      resources :displasia
      resources :esclerosis
    end
  end
end

app/models/read.rb
class Read < ActiveRecord::Base
  belongs_to :patient
  
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  def index
    @patients=Patient.all
    
  end
  
  def show
    @patients=Patient.find(:id)
    @reports = Report.where(user_id: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
    
  end
  
  
  
  
end

app/helpers/reads_helper.rb
module ReadsHelper

  def study_button15(pat,eq)
    if pat.reports.where(user_id: current_user.id).map{|r| r.equipment}.include?(eq)
 content_tag(:button, pat.code, class: 'btn disabled')
    else
 link_to pat.code, new_patient_report_path(pat, equipment: eq, label:pat.code), class: 'btn btn-primary enabled'
    end
  end
  
  def study_button3(pat,eq)
    if pat.reports.where(user_id: current_user.id).map{|r| r.equipment}.include?(eq)
      content_tag(:button, "S#{pat.cod3t}", class: 'btn disabled')
    else
      link_to "S#{pat.cod3t}", new_patient_report_path(pat, equipment: eq,label:"S#{pat.cod3t}"), class: 'btn btn-primary enabled'
    end
  end
end

def duplicate_read(cod)
  user1=[54,4,41,21,1,25,31,29,56,51,40,14,9,52,26,2,38,27,19,18,10,60,4,47,15,55,33,43,59,13]
  user2=[12,50,8,46,47,16,32,17,28,39,58,35,30,6,42,34,24,3,49,48,22,53,37,36,45,23,5,11,57,20]
  
  if current_user.id==1
    codpat=user1[cod]
  else 
    codpat=user2[cod]
  end
  
  if codpat <31
    if codpat <10
        codpat="S0#{codpat}"
    else
        codpat="S#{codpat}"
    end
    patienti=Patient.find_by_code(codpat)
    eq="1.5T"
  else
    patienti=Patient.find_by_cod3t(codpat)
    eq="3T"
  end
  

  
  if patienti.reports.where(user_id: current_user.id).map{|r| r.label}.include?("S#{cod+61}")
    content_tag(:button, codpat, class: 'btn disabled')
    ena="false";
  else
    ena="true";
  end
  outdata=[patienti,eq,ena] 
   return outdata
end

app/views/reads/index.html.erb
<h1>Listado de pacientes</h1>

<div class="page-header">
  <h2>Listado de pacientes</h2>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Paciente</th>
      <!--<th>Edad</th>
      <th>Sexo</th>
      <th>Lecturas</th>-->
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><strong><%= patient.code %></strong></td>
        <!--<td><%= patient.age %></td> 
        <td><%= patient.sex %></td> -->
        <td>
          <%= study_button15(patient,'1.5T') %>
        </td>
		<td><%=link_to "mostrar reportes", patient_reports_path(patient ,equipment: "1.5T",banddob: "false",label:patient.code), class: 'btn btn-primary enabled' %></td>
		
	</tr>
	<% end %>

	<!-- LECTURA DE 3T -->
	<%@code3T=*(31..60)%>
	
    <% @code3T.each do |cod| %>
	<tr>
			<%patienti=Patient.find_by_cod3t(cod)%>
			<td><strong><%= "S#{patienti.cod3t}" %></strong></td>
          <td>	<%= study_button3(patienti,'3T') %></td>
		  <td><%=link_to "mostrar reportes", patient_reports_path(patienti ,equipment: "3T",label:"S#{patienti.cod3t}",banddob:"true"), class: 'btn btn-primary enabled' %></td>
        
      </tr>
    <% end %>
	
	<!--LECTURA DUPLICADA-->
	<%@numdop=*(0..29)%>
	<%@numdop.each do |cod| %>
	<tr>
		<%@outputdata=duplicate_read(cod)%>	
		<td><strong><%="S#{cod+61}"%></strong></td>
		<%if @outputdata[2]=="true"%>
		<td><%=link_to "S#{cod+61}", new_patient_report_path(@outputdata[0], equipment:@outputdata[1], label:"S#{cod+61}", bandob:"true"), class: 'btn btn-primary enabled'%></td>
		<%else%>
		<td><%= content_tag(:button, "S#{cod+61}", class: 'btn disabled')%></td>
		<%end%>
		<td><%=link_to "mostrar reportes", patient_reports_path( @outputdata[0],equipment: @outputdata[1],label:"S#{cod+61}",banddob:"true"), class: 'btn btn-primary enabled' %></td>
	</tr>
	<%end%>
	
	
	
  </tbody>
</table>

app/views/reads/show.html.erb
<div class="page-header">
  <h3>Listado de reportes por <strong><%=current_user.name %></strong> para el paciente <strong><%= @patient.code %></strong></h3>
  <div class="pull-right">
 <%= link_to 'Listar pacientes', patients_path, class: 'btn'%>
 </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Paciente</th>
      <th>Equipo</th>
      <th>Fecha</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><strong><%= report.patient.code %></strong></td>
        <td><%= report.equipment %></td>
        <td><%= report.created_at %></td>

		<td><%=link_to "Ver", patient_report_path(@patient,report), class: 'btn btn-primary enabled' %></td>
		<td><%=link_to "Editar", edit_patient_report_path(@patient,report, equipment: report.equipment), class: 'btn btn-primary enabled' %></td>

		<td><%= link_to 'Eliminar',
                      patient_report_path(@patient,report),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Está seguro que quiere eliminar el reporte?')) },
                      :class => 'btn btn-danger' %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>