config/routes.rb
Epilady::Application.routes.draw do
        
  authenticated :user do
    root :to => 'reads#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :reads
  resources :prints
  resources :patients do
          
    resources :reports do
            get 'print'        
      resources :conclusions
      resources :tumors
      resources :malformacions
      resources :displasia
      resources :esclerosis
    end
  end
end

app/models/esclerosi.rb
class Esclerosi < ActiveRecord::Base
  attr_accessible :atrofia_sunj,
    :esclerosis,
    :estructura_anormal,
    :hallazgos_extra,
    :hiperintensidad,
    :volumenhipoder,
    :volumenhipoiz,
    :report_id
end

app/controllers/esclerosis_controller.rb
class EsclerosisController < ApplicationController

  # GET /esclerosis
  # GET /esclerosis.json
  def index
    @esclerosis = Esclerosi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @esclerosis }
    end
  end

  # GET /esclerosis/1
  # GET /esclerosis/1.json
  def show
    @esclerosi = Esclerosi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @esclerosi }
    end
  end

  # GET /esclerosis/new
  # GET /esclerosis/new.json
  def new
    @esclerosi = Esclerosi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @esclerosi }
    end
  end

  # GET /esclerosis/1/edit
  def edit
    @esclerosi = Esclerosi.find(params[:id])
  end

  # POST /esclerosis
  # POST /esclerosis.json
  def create
    @esclerosi = Esclerosi.new(params[:esclerosi])

    respond_to do |format|
      if @esclerosi.save
        format.html { redirect_to @esclerosi, notice: 'Esclerosi was successfully created.' }
        format.json { render json: @esclerosi, status: :created, location: @esclerosi }
      else
        format.html { render action: "new" }
        format.json { render json: @esclerosi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /esclerosis/1
  # PUT /esclerosis/1.json
  def update
    @esclerosi = Esclerosi.find(params[:id])

    respond_to do |format|
      if @esclerosi.update_attributes(params[:esclerosi])
        format.html { redirect_to @esclerosi, notice: 'Esclerosi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @esclerosi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /esclerosis/1
  # DELETE /esclerosis/1.json
  def destroy
    @esclerosi = Esclerosi.find(params[:id])
    @esclerosi.destroy

    respond_to do |format|
      format.html { redirect_to esclerosis_url }
      format.json { head :no_content }
    end
  end
end

app/views/esclerosis/_fields.html.erb
<h4>1. Esclerosis hipocampal:</h4>
<small>Zonas a ser inspeccionadas: Lóbulo temporal mesial, hipocampo, giro parahipocampal, amígdala</small>
<h6>Hallazgos a explorar:</h6>

<%= rf.simple_fields_for :esclerosi, @report.esclerosi do |f| %>

  <%= f.input :atrofia_sunj, collection: @laterality, as: :radio_buttons, item_wrapper_class: 'inline',
                    label: 'Volumen del hipocampo al ojo desnudo. Atrofia?' %>

  <%= f.input :hiperintensidad, collection: @laterality, as: :radio_buttons, item_wrapper_class: 'inline',
                    label: 'Hiperintensidad en T2 y FLAIR:' %>

  <%= f.input :estructura_anormal, collection: @laterality, as: :radio_buttons, item_wrapper_class: 'inline',
                    label: 'Superficie y estructura interna del hipocampo en T1. Anormal?' %>

  <%= f.input :estructura_anormal, label: 'Escriba el hallazgo extra hipocampal encontrado:' %>

  <h6>Conclusión</h6>
  <%= f.input :esclerosis, collection: @laterality, as: :radio_buttons, item_wrapper_class: 'inline',
                    label: 'Esclerosis hipocampal?' %>

<%end%>

app/views/esclerosis/_form.html.erb
<%= form_for @esclerosi, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :atrofia_sunj, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :atrofia_sunj, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hiperintensidad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :hiperintensidad, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :estructura_anormal, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :estructura_anormal, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :volumen, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :volumen, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :esclerosis, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :esclerosis, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hallazgos_extra, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :hallazgos_extra, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :report_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :report_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                esclerosis_path, :class => 'btn' %>
  </div>
<% end %>

app/views/esclerosis/edit.html.erb
<%- model_class = Esclerosi -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/esclerosis/index.html.erb
<%- model_class = Esclerosi -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:atrofia_sunj) %></th>
      <th><%= model_class.human_attribute_name(:hiperintensidad) %></th>
      <th><%= model_class.human_attribute_name(:estructura_anormal) %></th>
      <th><%= model_class.human_attribute_name(:volumen) %></th>
      <th><%= model_class.human_attribute_name(:esclerosis) %></th>
      <th><%= model_class.human_attribute_name(:hallazgos_extra) %></th>
      <th><%= model_class.human_attribute_name(:report_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @esclerosis.each do |esclerosi| %>
      <tr>
        <td><%= link_to esclerosi.id, esclerosi_path(esclerosi) %></td>
        <td><%= esclerosi.atrofia_sunj %></td>
        <td><%= esclerosi.hiperintensidad %></td>
        <td><%= esclerosi.estructura_anormal %></td>
        <td><%= esclerosi.volumen %></td>
        <td><%= esclerosi.esclerosis %></td>
        <td><%= esclerosi.hallazgos_extra %></td>
        <td><%= esclerosi.report_id %></td>
        <td><%=l esclerosi.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_esclerosi_path(esclerosi), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      esclerosi_path(esclerosi),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_esclerosi_path,
            :class => 'btn btn-primary' %>

app/views/esclerosis/new.html.erb
<%- model_class = Esclerosi -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/esclerosis/show.html.erb
<%- model_class = Esclerosi -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:atrofia_sunj) %>:</strong></dt>
  <dd><%= @esclerosi.atrofia_sunj %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hiperintensidad) %>:</strong></dt>
  <dd><%= @esclerosi.hiperintensidad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estructura_anormal) %>:</strong></dt>
  <dd><%= @esclerosi.estructura_anormal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:volumen) %>:</strong></dt>
  <dd><%= @esclerosi.volumen %></dd>
  <dt><strong><%= model_class.human_attribute_name(:esclerosis) %>:</strong></dt>
  <dd><%= @esclerosi.esclerosis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hallazgos_extra) %>:</strong></dt>
  <dd><%= @esclerosi.hallazgos_extra %></dd>
  <dt><strong><%= model_class.human_attribute_name(:report_id) %>:</strong></dt>
  <dd><%= @esclerosi.report_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              esclerosis_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_esclerosi_path(@esclerosi), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              esclerosi_path(@esclerosi),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>